### PR TITLE
adding option urlPrefixes ..

### PR DESCRIPTION
**Pull request by lietzi**
.. from Version 0.4.12 since updates from 1.5.0 break the desired behavior on asset-files uploaded to cdn

### CODE REVIEW

**Comment by tim-bradley** [comment]
@lietzi - As per my comments on #240, I think that this could be improved by:

1. Renaming `cdnPath` to say `uploadPath` because it makes more semantic sense.

2. And the replace function expanded to account for `srcset` which has urls followed by a space and preceded by either a " or ' or a ", " (comma + space). 

To cater for srcset but try limit errors, we could also push something like:

```
    if (opts.cdnPath) {
        replaceEnclosedBy.push([opts.cdnPath, '"']);
        replaceEnclosedBy.push([opts.cdnPath, "'"]);
        replaceEnclosedBy.push( "'" + [opts.cdnPath, " "]);
        replaceEnclosedBy.push( '"' + [opts.cdnPath, " "]);
        replaceEnclosedBy.push( ", " + [opts.cdnPath, " "]);
    }
```
Bare in mind I am not a coder, so I do not know if the two values can be concatenated like that or if they need to be wrapped or something.

Thank you for all your help - and I hope this gets merged.

**Comment by ArmorDarks** [comment]
`cdnPath` definitely confusion option. `uploadPath` doesn't seem to be right too.

First of all, it should be an array, because sometime you might need to specify multiple domains.

And it would make sense to call it `baseUrl`, or `absoluteUrl`. I'd pick `baseUrl` because `absoluteUrl` makes an impression that it contains full path, while we mean here only the first part of the URL, which will be later substituted.

> And the replace function expanded to account for srcset which has urls followed by a space and preceded by either a " or ' or a ", " (comma + space).

I wonder, why it needs to be enclosed by spaces?

**Comment by lietzi** [comment]
The cdnPath Option was introduced in Version 0.5 (after my PR #78 and Ben´s Merge in #101) in 2014 ;)
But in Version 1.0 this was not necessary anymore, because of the new replace-technique. But after Version 1.4.1 it does not work anymore - the new filter methods in Version 1.5.0 ignored my cdn-paths - so i reintroduced this with this PR in Oct 2017 because Version 1.6 is a lot faster than 1.4.1

It was only build for my very special own usecase - where i use this plugin in a static site builder, where all static files except the html-files where served from a different domain to avoid cookie-overhead and allow more parallel connections. back then i thought this might be useful to someone else.
Today with http2 i don´t use the cdnPath anymore.

That´s for the history - back to the current situation:
For naming maybe urlPrefixes fits better?
And i agree that in a more global usecase this would be more usefull as an array.
Feel free to PR ;)

For the srcset problem see #224 - and there the test-case in tests/imgsrcset/imgsrcset.html
thats a typical example for the srcset "problem".

**Comment by tim-bradley** [comment]
Regarding a more global use case, could we do something like:

    if (opts.urlPrefixes) {
        replaceEnclosedBy.push(opts.urlPrefixes);
    }

Where the value of `urlPrefixes` can be a custom list of sets of enclosures like:

 `["example1.com", " "], ["example1.com", ","], ['example1.com', '"'], ["example2.com", " "], ["example2com", ","], ['example2.com', '"']` 

A bit more detail required, but also more granular control. Good for replaces, but may break other parts?

**Comment by lietzi** [comment]
Hi.. i updated my PR accordingly..
urlPrefixes now accepts an Array of urls.

Furthermore nodejs 4 and 5 had reached EOL ;)

**Comment by tim-bradley** [comment]
@lietzi Awesome, man. Thanks.

Please @hollandben -> If you read this, could you consider accepting the PR?

**Comment by hollandben** [comment]
Published as version `1.7.0` 👍

**Comment by tim-bradley** [comment]
Thanks @lietzi , @ArmorDarks and, of course, @hollandben !

**Pull request merged**
