### PR TITLE
Add option to write the hash of the index file to a file

### PR DESCRIPTION
**Pull request by PLPeeters**
This PR adds an option to hash the index file and write its hash to another file that can then be fetched at regular intervals to check if the user should be asked to reload the page.

The reasoning behind this is modern web apps that do everything via AJAX often stay open in user's browsers for quite a while and could theoretically never get reloaded. Having the hash of the index file stored would enable apps to do an AJAX call against it to check if it changed and ask the user to reload the page if it did, solving this kind of problem.

### CODE REVIEW

**Comment by hollandben** [comment]
Hi @PLPeeters - could you not have another busting task to only hash the `index.html` file instead of adding additional options to the plugin?

**Comment by PLPeeters** [comment]
Hi @hollandben, 

I actually didn't think of that. However, this would in my opinion require too many additional steps:

If you're not using the queryString option, hashing index.html means it will be renamed to index.HASH.html, which means you _have_ to use the queryString option in order to prevent renaming the file. This might already be a problem for some people. 

Using the queryString option means you'll have to create two additional files if you don't have a separate build folder. Why? Say you have a file named `index_hash` which contains just `index.html`. If you run the plugin with the queryString option, it will then contain `index.html?123456789`. If you run it again, it will contain `index.html?123456789?123456789`, etc. This means you need to create a second file containing `index.html` that you copy before busting it, making this—in my opinion—ridiculously complicated.

If you want to simplify the options, we could leave only the `indexFilename` option that would be `undefined` by default. Specifying it would always write the hash of the file to the `INDEX_HASH` file, instead of the filename currently declared in the `indexHashFilename` option.

**Comment by hollandben** [comment]
The job of this task is to enable the user to point it at some files and references, hash them and update the references, nothing more. How the user sets up their build is entirely up to them.

> This means you need to create a second file containing index.html that you copy before busting it, making this—in my opinion—ridiculously complicated.

As I've stated in other PRs and issues, this may seem a bit long winded but it is a cleaner approach. Personally, all build steps in my projects are able to be run from any starting point, meaning that no matter how many times they run the results are the same. I don't see this as something `grunt-cache-bust` should be handling

**Comment by PLPeeters** [comment]
I find it counter-intuitive to have to reference index.html in another file, since it's the only file that is never referenced in another one, given it's the entry point. The current set of options make it necessary to create a file that doesn't have a clear purpose at first glance, which I find unnecessarily confusing. Besides, there's still the issue that this use case forces the user to use the queryString option, which they might not want to do.

**Pull request closed without merging**
