### PR TITLE
Fix paths in hashed files

### PR DESCRIPTION
**Pull request by richardhinkamp**
Fixes for #207 

It correctly identifies all relative paths from the source file to the hashed filename, including the absolute path. 

The replace is smarter now, a replace of "css/app.css" would also replace "lib/css/app.css", which is incorrect. So now the filename is only replaced in these cases, enclosed by:
`"{file}"`
`'{file}'`
`({file})` (css url(...))
`={file}>` (unquoted html attribute)
`={file}\s` (unquoted html attribute followed by more attributes)
Since the filename may contain a querystring, the closing char may also be a '?'.
I created a new unit test for this.

~~If a file is copied to a hashed filename, replacing will now happen in the hashed file instead of the original file, since the original file will not be used (and maybe even be deleted).~~
If a full filename is specified as source instead of a wildcard and that file is busted, the source cannot be found when replacing in files. It now correctly handles this cases and translated the filename to the busted filename.

All the test still work and the test project in the issue also works as expected. I hope this a correct change which can be merged, I would love to get some feedback on it.

Richard

### CODE REVIEW

**Comment by richardhinkamp** [comment]
@hollandben are you willing to accept (or at least review) this PR? Can I help to get this merged?

**Comment by zacyang** [comment]
Can we please merge this PR, I have encountered the similar issue regarding the relative path as well. Thanks.

**Comment by richardhinkamp** [comment]
@hollandben are you planning to do something with this PR?

**Comment by hollandben** [comment]
Hi @richardhinkamp and @zacyang. It appears your changes have broken parsing of files that include an "alternate syntax" (#214). I've created a test for it that is currently failing and pushed it into the `alternate-syntax-parsing-broken` branch. Could either of you please have a look into fixing this - thanks.

**Comment by richardhinkamp** [comment]
Thanks for merging @hollandben ! I will comment in #214 about that issue

**Pull request merged**
